---
title: "Example of applications of document treatment for preparing the extraction phase"
author: "Marius Bottin"
date: "`r Sys.Date()`"
output: 
  github_document:
     number_sections: true
     toc: true
---



```{r}
load("../../screening/fullTextScreening/acceptedFinal.RData")
AcceptedFinal<-unique(AcceptedFinal)
load("../../screening/fullTextScreening/FTS.RData")
source("./docAssignment_functions.R")
RT<-reviewTable(FTS)
RT_ok<-RT[rownames(RT)%in%AcceptedFinal,]
nbDocFTS<-colSums(RT_ok[,FTS$description$people])
nbDocFTS<-nbDocFTS[order(nbDocFTS)]
prioridad<-lapply(FTS$description$people,function(x)return(character(0L)))
names(prioridad)<-FTS$description$people
prioridad$Ana<- c("Aksel_Stenberdt2023","Aksut2016","Arya2016","Baker2013","Le2019", "Lambert2012", "Gold2015", "Monroe2016", "Salas_Rueda2021", "Hugel2022")
prioridad$Ana<-prioridad$Ana[prioridad$Ana%in%AcceptedFinal]
nbToGive<-c(Ana=45,Marius=NA,Benjamin=15,Sara=15,JuanGabriel=15,Luisa=15,Sergio=15)
(nbToGive["Marius"]<-length(AcceptedFinal)-sum(nbToGive,na.rm = T))
for (i in 1:length(nbDocFTS))
{
  person<-names(nbDocFTS)[i]
  alreadyIn<-length(prioridad[[person]])
  toGive<-nbToGive[person]
  docPotential<-sum(RT_ok[!rownames(RT_ok)%in%unlist(prioridad),person])
  nb<-min(c(docPotential,toGive))-alreadyIn
  rt_potential<-RT_ok[as.logical(RT_ok[,person])&!rownames(RT_ok)%in%unlist(prioridad),]
  rt_potential<-rt_potential[order(rt_potential$Ana,rt_potential$Marius,rt_potential$Sergio,rt_potential$Luisa,method="radix",decreasing=T),]
  prioridad[[person]]<-c(prioridad[[person]],rownames(rt_potential)[1:nb])
}
AcceptedFinal[!AcceptedFinal%in%unlist(prioridad)]
nbToGive<-nbToGive[names(prioridad)]
stillToGive<-nbToGive-sapply(prioridad,length)
attrib<-prioridad
for(i in 1:length(stillToGive))
{
  if(stillToGive[i]==0){next}
  person<-names(stillToGive)[i]
  docsConcerned<-AcceptedFinal[!AcceptedFinal%in%unlist(attrib)]
  attrib[[person]]<-c(attrib[[person]],docsConcerned[1:stillToGive[i]])
}
docExtract<-lapply(attrib,function(x)na.omit(x))
```


```r
save(docExtract,file="../../extraction/docExtract.RData")
```


```{r}
createDirPdf<-function(name,listAbbrev,rootDir,pdfDir)
{
  DIR<-paste0(rootDir,"/",name)
  if(dir.exists(DIR))
  {
    unlink(DIR,recursive=T)
  }
  dir.create(paste0(rootDir,"/",name))
  lapply(listAbbrev,function(x){
    system(paste0("ln ",pdfDir,"/",x,".pdf ",DIR))
  })
}
for(i in 1:length(docExtract)){
  createDirPdf(names(docExtract)[i],docExtract[[i]],"../../extraction/","../../PDF_included_total/")
}
