---
title: "Searching words in the pdfs"
author: "Marius Bottin"
date: "`r Sys.Date()`"
output: 
  bookdown::github_document2:
     number_sections: true
     toc: true
always_allow_html: true
---


```{r}
require(knitr)&require(kableExtra)
knitr::opts_chunk$set(cache=T)
dos <- normalizePath("../../extraction/")
```
# Number of pages

```{r}
setwd(dos)
raw <- system(paste("find",'-type d','-exec exiftool -T -filename -PageCount -s3 -ext pdf {} \\;'),intern = T)
sum(as.numeric(sapply(strsplit(raw,"\t"),function(x)x[2])))
```

# Self-efficacy

"Self-efficacy" or "self efficacy":

```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "self[ -]efficacy" {} \\;'),intern = T)
sep <- strsplit(raw,":")
kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
```


# Theory of planned behavior

```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "planned[ -]behaviou?r" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep1<-sep
kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
```


# Controversy

## Controvers

```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "controvers" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep1<-sep
kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
```


## Belief

```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "belief" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep2<-sep
kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
```

## Opinion

```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "opinion" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep3<-sep
kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
```

## Republican

```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "republican" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep4<-sep
kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
```


## Human-induced

```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "human-induced" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep5 <- sep
kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
```

## All controversy table


```{r}
all(sapply(sep1,function(x)x[1])==sapply(sep2,function(x)x[1]))
all(sapply(sep1,function(x)x[1])==sapply(sep3,function(x)x[1]))
all(sapply(sep1,function(x)x[1])==sapply(sep4,function(x)x[1]))
all(sapply(sep1,function(x)x[1])==sapply(sep5,function(x)x[1]))
allControv<-data.frame(
  controvers=as.integer(sapply(sep1,function(x)x[2])),
  belief=as.integer(sapply(sep2,function(x)x[2])),
  opinion=as.integer(sapply(sep3,function(x)x[2])),
  republican=as.integer(sapply(sep4,function(x)x[2])),
  humanInduced=as.integer(sapply(sep5,function(x)x[2]))
)
rownames(allControv)<-sapply(sep1,function(x)x[1])
#allControv<-allControv[rowSums(allControv)>1,]
 allControv$SUM<-rowSums(allControv)
# allControv[1:5]<-lapply(allControv[1:5], function(x) {
#     cell_spec(x, bold = T, 
#               color = spec_color(x, end = 0.9),
#               font_size = spec_font_size(x))
# })
# allControv[6]<-cell_spec(allControv[[6]], color = "white", bold = T,
#     background = spec_color(1:10, end = 0.9, option = "A", direction = -1))
kbl(allControv, escape = F, align = "c") %>%
  kable_classic("striped", full_width = F)
```



# Earthquakes

"Earthq\*"

```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "earthq" {} \\;'),intern = T)
sep <- strsplit(raw,":")
kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
```

"se?ism*"

```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "se?ism" {} \\;'),intern = T)
sep <- strsplit(raw,":")
kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
```

# Misconception


```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "misconception" {} \\;'),intern = T)
sep <- strsplit(raw,":")
kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
```

# Outcomes



```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "behaviou?r" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep_behavior<-sep
#kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
outcomes<-data.frame(behavior=as.integer(sapply(sep,function(x)x[2])),
                     row.names=sapply(sep,function(x)x[1]))
```


```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "attitude" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep_attitude<-sep
#kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
outcomes$attitude<-as.integer(sapply(sep,function(x)x[2]))
```


```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "knowledge" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep_knowledge<-sep
#kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
outcomes$knowledge<-as.integer(sapply(sep,function(x)x[2]))
```


```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "understand*" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep_understanding<-sep
#kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
outcomes$understand<-as.integer(sapply(sep,function(x)x[2]))
```


```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "aware" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep_awareness<-sep
#kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
outcomes$aware<-as.integer(sapply(sep,function(x)x[2]))
```

```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "belief" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep_belief<-sep
#kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
outcomes$belief<-as.integer(sapply(sep,function(x)x[2]))
```

```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "conscious" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep_conscious<-sep
#kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
outcomes$conscious<-as.integer(sapply(sep,function(x)x[2]))
```

```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e " concern(ed)? " {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep_concern<-sep
#kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
outcomes$concern<-as.integer(sapply(sep,function(x)x[2]))
```




```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "emot" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep_emot<-sep
#kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
outcomes$emot<-as.integer(sapply(sep,function(x)x[2]))
```



```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "hope" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep_emot<-sep
#kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
outcomes$hope<-as.integer(sapply(sep,function(x)x[2]))
```


```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "fear" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep_fear<-sep
#kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
outcomes$fear<-as.integer(sapply(sep,function(x)x[2]))
```

```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "empath" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep_empath<-sep
#kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
outcomes$empath<-as.integer(sapply(sep,function(x)x[2]))
```


```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "worr" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep_worr<-sep
#kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
outcomes$worr<-as.integer(sapply(sep,function(x)x[2]))
```


```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "feeling" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep_feeling<-sep
#kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
outcomes$feeling<-as.integer(sapply(sep,function(x)x[2]))
```


```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "willingness to" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep_willingness_to<-sep
#kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
outcomes$willingness_to<-as.integer(sapply(sep,function(x)x[2]))
```


```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "intent" {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep_intent<-sep
#kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
outcomes$intent<-as.integer(sapply(sep,function(x)x[2]))
```



```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e " habits? " {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep_habit<-sep
#kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
outcomes$habit<-as.integer(sapply(sep,function(x)x[2]))
```


```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e " actions? " {} \\;'),intern = T)
sep <- strsplit(raw,":")
sep_habit<-sep
#kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
outcomes$action<-as.integer(sapply(sep,function(x)x[2]))
```


## recapitulative table: outcomes


```{r}
kable(outcomes)%>%
  add_header_above(c(" "=1,"General"=2,"Knowledge"=2,"awareness"=3,"emotion"=7,"intent"=2,"habit"=1,"action"=1))
```

