---
title: "Searching words in the pdfs"
author: "Marius Bottin"
date: "`r Sys.Date()`"
output: 
  bookdown::github_document2:
     dev: "jpeg"
     dpi: 600
     number_sections: true
     toc: true
always_allow_html: true
---


```{r}
require(knitr)&require(kableExtra)
knitr::opts_chunk$set(cache=T, fig.path="./Fig/")
dos <- normalizePath("../../extraction/")
```
# Number of pages

```{r}
setwd(dos)
raw <- system(paste("find",'-type d','-exec exiftool -T -filename -PageCount -s3 -ext pdf {} \\;'),intern = T)
numberPages <- as.data.frame(Reduce(rbind,strsplit(raw,"\t")))
sum(as.numeric(sapply(strsplit(raw,"\t"),function(x)x[2])))
```

# Psycho

```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "psycho" {} \\;'),intern = T)
sep <- strsplit(raw,":")
```


```{r}
cat("Number of papers: ", sum(sapply(sep,function(x)as.numeric(x[2])>=5)), "/", length(sep), "include the word 5 times or more\n" )

kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
```


```{r}
tabOccurrences<-data.frame(
  pdfName=basename(sapply(sep,function(x)x[1])),
  occurrences=as.numeric(sapply(sep,function(x)x[2]))
)
tabOccurrences$pages<-as.numeric(numberPages[match(tabOccurrences$pdfName,numberPages$V1),2])
occPerPage<-tabOccurrences$occurrences/tabOccurrences$pages

hist(tabOccurrences$occurrences,xlab="Number of occurrences",nclass=60, main='*psycho*',ylab="Number of documents")
hist(occPerPage,xlab="Number of occurrences per page",nclass=60, main='*psycho*',ylab="Number of documents")

```

# Self-efficacy

"Self-efficacy" or "self efficacy":

```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "self.efficacy" {} \\;'),intern = T)
sep <- strsplit(raw,":")
```


```{r}
cat("Number of papers: ", sum(sapply(sep,function(x)as.numeric(x[2])>=5)), "/", length(sep), "include the word 5 times or more\n" )
kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
```


```{r}
tabOccurrences<-data.frame(
  pdfName=basename(sapply(sep,function(x)x[1])),
  occurrences=as.numeric(sapply(sep,function(x)x[2]))
)
tabOccurrences$pages<-as.numeric(numberPages[match(tabOccurrences$pdfName,numberPages$V1),2])
occPerPage<-tabOccurrences$occurrences/tabOccurrences$pages

hist(tabOccurrences$occurrences,xlab="Number of occurrences",nclass=60, main='*self.efficacy*',ylab="Number of documents")
hist(occPerPage,xlab="Number of occurrences per page",nclass=60, main='*self.efficacy*',ylab="Number of documents")
```


# Theory of planned behavior

```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "planned[ -]behaviou?r" {} \\;'),intern = T)
sep <- strsplit(raw,":")
```


```{r}
cat("Number of papers: ", sum(sapply(sep,function(x)as.numeric(x[2])>=5)), "/", length(sep), "include the word 5 times or more\n" )
sep1<-sep
kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
```


```{r}
tabOccurrences<-data.frame(
  pdfName=basename(sapply(sep,function(x)x[1])),
  occurrences=as.numeric(sapply(sep,function(x)x[2]))
)
tabOccurrences$pages<-as.numeric(numberPages[match(tabOccurrences$pdfName,numberPages$V1),2])
occPerPage<-tabOccurrences$occurrences/tabOccurrences$pages

hist(tabOccurrences$occurrences,xlab="Number of occurrences",nclass=60, main='*planned.behaviou?r*',ylab="Number of documents")
hist(occPerPage,xlab="Number of occurrences per page",nclass=60, main='*planned.behaviou?r*',ylab="Number of documents")
```


# Hope


```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "hope" {} \\;'),intern = T)
sep <- strsplit(raw,":")
```


```{r}
cat("Number of papers: ", sum(sapply(sep,function(x)as.numeric(x[2])>=5)), "/", length(sep), "include the word 5 times or more\n" )
kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
```


```{r}
tabOccurrences<-data.frame(
  pdfName=basename(sapply(sep,function(x)x[1])),
  occurrences=as.numeric(sapply(sep,function(x)x[2]))
)
tabOccurrences$pages<-as.numeric(numberPages[match(tabOccurrences$pdfName,numberPages$V1),2])
occPerPage<-tabOccurrences$occurrences/tabOccurrences$pages

hist(tabOccurrences$occurrences,xlab="Number of occurrences",nclass=60, main='*hope*',ylab="Number of documents")
hist(occPerPage,xlab="Number of occurrences per page",nclass=60, main='*hope*',ylab="Number of documents")
```

# Fear


```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "fear" {} \\;'),intern = T)
sep <- strsplit(raw,":")
```


```{r}
cat("Number of papers: ", sum(sapply(sep,function(x)as.numeric(x[2])>=5)), "/", length(sep), "include the word 5 times or more\n" )
kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
```


```{r}
tabOccurrences<-data.frame(
  pdfName=basename(sapply(sep,function(x)x[1])),
  occurrences=as.numeric(sapply(sep,function(x)x[2]))
)
tabOccurrences$pages<-as.numeric(numberPages[match(tabOccurrences$pdfName,numberPages$V1),2])
occPerPage<-tabOccurrences$occurrences/tabOccurrences$pages

hist(tabOccurrences$occurrences,xlab="Number of occurrences",nclass=60, main='*fear*',ylab="Number of documents")
hist(occPerPage,xlab="Number of occurrences per page",nclass=60, main='*fear*',ylab="Number of documents")
```

# Distress


```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "distress" {} \\;'),intern = T)
sep <- strsplit(raw,":")
```


```{r}
cat("Number of papers: ", sum(sapply(sep,function(x)as.numeric(x[2])>=5)), "/", length(sep), "include the word 5 times or more\n" )
kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
```


```{r}
tabOccurrences<-data.frame(
  pdfName=basename(sapply(sep,function(x)x[1])),
  occurrences=as.numeric(sapply(sep,function(x)x[2]))
)
tabOccurrences$pages<-as.numeric(numberPages[match(tabOccurrences$pdfName,numberPages$V1),2])
occPerPage<-tabOccurrences$occurrences/tabOccurrences$pages

hist(tabOccurrences$occurrences,xlab="Number of occurrences",nclass=60, main='*distress*',ylab="Number of documents")
hist(occPerPage,xlab="Number of occurrences per page",nclass=60, main='*distress*',ylab="Number of documents")
```

# anxi


```{r}
setwd(dos)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "anxi" {} \\;'),intern = T)
sep <- strsplit(raw,":")
```


```{r}
cat("Number of papers: ", sum(sapply(sep,function(x)as.numeric(x[2])>=5)), "/", length(sep), "include the word 5 times or more\n" )
kable(Reduce(rbind,sep[sapply(sep,function(x)as.numeric(x[2])>1)]),row.names = NA)
```


```{r}
tabOccurrences<-data.frame(
  pdfName=basename(sapply(sep,function(x)x[1])),
  occurrences=as.numeric(sapply(sep,function(x)x[2]))
)
tabOccurrences$pages<-as.numeric(numberPages[match(tabOccurrences$pdfName,numberPages$V1),2])
occPerPage<-tabOccurrences$occurrences/tabOccurrences$pages

hist(tabOccurrences$occurrences,xlab="Number of occurrences",nclass=60, main='*anxi*',ylab="Number of documents")
hist(occPerPage,xlab="Number of occurrences per page",nclass=60, main='*anxi*',ylab="Number of documents")
```


# Subset in psychology journals

```{r}
dosPsycho <- normalizePath("../../CCE and Psychology/")
setwd(dosPsycho)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "psycho" {} \\;'),intern = T)
sep <- strsplit(raw,":")
```

```{r}
tabOccurrences<-data.frame(
  pdfName=basename(sapply(sep,function(x)x[1])),
  occurrences=as.numeric(sapply(sep,function(x)x[2]))
)
tabOccurrences$pages<-as.numeric(numberPages[match(tabOccurrences$pdfName,numberPages$V1),2])
occPerPage<-tabOccurrences$occurrences/tabOccurrences$pages

hist(tabOccurrences$occurrences,xlab="Number of occurrences",nclass=60, main='*psycho*',ylab="Number of documents")
hist(occPerPage,xlab="Number of occurrences per page",nclass=60, main='*psycho*',ylab="Number of documents")
```


```{r}
dosPsycho <- normalizePath("../../CCE and Psychology/Education journals/")
setwd(dosPsycho)
raw <- system(paste("find",'-name "*.pdf"','-exec pdfgrep -icH -e "psycho" {} \\;'),intern = T)
sep <- strsplit(raw,":")
```

```{r}
tabOccurrences<-data.frame(
  pdfName=basename(sapply(sep,function(x)x[1])),
  occurrences=as.numeric(sapply(sep,function(x)x[2]))
)
tabOccurrences$pages<-as.numeric(numberPages[match(tabOccurrences$pdfName,numberPages$V1),2])
occPerPage<-tabOccurrences$occurrences/tabOccurrences$pages

hist(tabOccurrences$occurrences,xlab="Number of occurrences",nclass=60, main='*psycho*',ylab="Number of documents")
hist(occPerPage,xlab="Number of occurrences per page",nclass=60, main='*psycho*',ylab="Number of documents")
```
